### ISSUE TITLE
Gem Development guide improvements

### ISSUE THREAD

**Issue by EduardoBautista** [radar/guides#67]
This issue is to help me keep track of things I need to help bring up to date in order to use the guide on http://bundler.io.

**Todos:**
- [x] bin/foodie -> exe/foodie
- [x] Mention the `CONTRIBUTING.md` and `README.md` files
- [x] Use the newest version of activesupport and rspec and use the `expect` syntax instead of `should`
- [x] New gems now begin on version 0.1.0 instead of 0.0.1
- [x] Mention the Bundler version that the guide is being written for (Bundler 1.9 at the moment)

If there are any other issues let me know, I will be going through the tutorial again with the code I rewrite to catch any issues.

**Comment by revolter** [comment]
So should the executable be in `bin` or `exe`?

**Comment by radar** [comment]
Generated `gemspec` files specify `bindir` as `exe`, so I think `exe` is the correct directory. `bin` is seemingly for local gem development purposes (contains a `setup` file)

**Comment by revolter** [comment]
But the `gemspec` is generated by `bundler` which might be subjective, as I didn't see any gem using an `exe` directory.

**Comment by revolter** [comment]
Also, even `foodie` from the guide is in `bin`: https://github.com/radar/guides/blob/master/gem-development/foodie/bin/foodie.

**Comment by radar** [comment]
This is the authoritative source: https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/newgem.gemspec.tt. bindir here uses exe. Likely foodie uses bin because it was generated before Bundler changed from using bin to using exe.

**Comment by revolter** [comment]
For others that may stumble upon this, here is some background info about the change which clearly explains the difference: http://bundler.io/blog/2015/03/20/moving-bins-to-exe.html.
